### ISSUE TITLE
Synthax question : centroid or descriptor

### ISSUE THREAD

**Issue by felixchalumeau** [resibots/pymap_elites#10]
Just to be sure, in this [line](https://github.com/resibots/pymap_elites/blob/master/map_elites/cvt.py#L52) and the following one, of the definition of `__add_to_archive`. What does the variable `centroid` refers to? 

It looks like the second argument of `__add_to_archive` when used in `compute` [here](https://github.com/resibots/pymap_elites/blob/master/map_elites/cvt.py#L124) corresponds to the descriptor of a solution, rather than the centroid. (I assume that centroid and descriptor are different as they are two differents attributes in the definition of [species](https://github.com/resibots/pymap_elites/blob/master/map_elites/common.py#L79).

Hence my two questions:
- what is a centroid? 
- shouldn't we use the name `descriptor` in the definition of the `__add_to_archive` function instead of `centroid`?

**Comment by jbmouret** [comment]
Hi

First, please note that this is an implementation of CVT-MAP-Elites, therefore the niches are defined by a centrical Voronoi Tesselation and not by a grid like in the basic MAP-Elites. Each niche is described by a centroid (the center of the niche). Please see:
https://arxiv.org/pdf/1610.05729.pdf 

In that implementation, the centroid is the descriptor of the center of the niche, not of the individual.

That said, you are right that `add_to_archive` actually takes a descriptor, and the actual centroid is retrieved at the first line: `    niche_index = kdt.query([centroid], k=1)[1][0][0]` (which finds the closest centroid) from the KD-tree.

We should fix this. Thanks for pointing this out.

**Comment by felixchalumeau** [comment]
Thank you for your answer. This is perfectly clear now.
